version: '3.3'
services:
    php:
        container_name: ui-studentlist
        ports:
            - '8000:80'
        networks: 
            - studentlist-network
        volumes:
            - '$PWD/website:/var/www/html'
        environment:
            - USERNAME=toto
            - PASSWORD=python
        image: 'php:apache'
        depends_on:
            - studentlist    
        
    studentlist:
        container_name: studentlis-test
        networks: 
            - studentlist-network
        volumes:
            - '$PWD/simple_api/student_age.json:/data/student_age.json'
        image: studentlist:v1

    registry:
        container_name: registry
        networks: 
            - registry-network
        image: registry:2
        ports:
            - '5000:5000'

    registry-ui:
        container_name: registry-ui
        networks: 
            - registry-network
        image: joxit/docker-registry-ui:static
        environment:
            - REGISTRY_URL="http://registry:5000"
            - REGISTRY_TITLE="ULRICH PRIVATE REGISTRY"
        ports:
            - '8080:80'
networks: 
    studentlist-network:
    registry-network:
